#!/bin/bash
#
# Perform necessary puppet setup steps
# after package is installed.
#


prefix="contegix-"
puppet_services="puppet-agent " 
install_base="/opt/contegix/puppet"
if [ -f /etc/redhat-release ]; then
  	os_family="RedHat"
	os_major_rev="$(perl -pe 's/.*release (\d+)\.\d+.*/$1/' /etc/redhat-release)"
else
  	os_family="Unknown"
	os_major_rev="Unknown"
fi

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

for service in $puppet_services; do
	if [ ! -e /etc/init.d/${prefix}$service ] ; then 
		ln -s /opt/contegix/puppet/etc/init.d/$service /etc/init.d/${prefix}${service}
		chkconfig --add ${prefix}$service
		chkconfig ${prefix}$service off
	fi
done

# link logrotate configuration
[ -h /etc/logrotate.d/${prefix}puppet ] || ln -s /opt/contegix/puppet/etc/logrotate.d/puppet /etc/logrotate.d/${prefix}puppet
# link hourly puppet agent cron
[ -h /etc/cron.hourly/${prefix}puppet-agent ] || ln -s ${install_base}/etc/cron.hourly/puppet-agent /etc/cron.hourly/${prefix}puppet-agent

if [ "${os_major_rev}" == "7" -a "${os_family}" == "RedHat" ] ; then	
	[ -h /etc/systemd/system/${prefix}puppet-agent.service ] || ln -s ${install_base}/etc/systemd/system/contegix-puppet-agent.service /etc/systemd/system/${prefix}puppet-agent.service	
	systemctl daemon-reload
	systemctl disable contegix-puppet-agent.service
else
fi

exit 0
